version: '3.7'

services:
  core:
    image: ros:melodic-ros-core-bionic
    restart: always
    ports:
      - "11311:11311"
    command: ["/opt/ros/melodic/bin/roscore"]
    networks:
    - ros

  debug:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/ros:latest
    restart: always
    working_dir: /var/code
    command: ["/var/code/utils/start-echo-node.sh", "/fromweb"]
    environment:
      ROS_MASTER_URI: http://core:11311
    volumes:
      - /home/streetbot/Desktop/Workspace/vr2-arduino:/var/code
    networks:
    - ros

  webNode:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/ros:latest
    restart: always
    working_dir: /var/code
    volumes:
    - ./:/var/code
    devices:
      - "/dev/video7:/dev/video0"
    command: ["/var/code/robot"]  # This requires the binary be built for the specific OS
    environment:
      ROS_MASTER_URI: http://core:11311
      ENV: robot
    networks:
    - ros

  vr2Node:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/ros:latest
    restart: always
    working_dir: /var/code
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    command: ["/var/code/utils/start-vr2-node.sh", "/dev/ttyACM0"]
    environment:
      ROS_MASTER_URI: http://core:11311
    volumes:
      - /home/streetbot/Desktop/Workspace/vr2-arduino:/var/code
    networks:
    - ros

  lidarNode:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/lidar-node:latest
    restart: always
    working_dir: /usr/src/app
    devices:
      - "/dev/ydlidar:/dev/ydlidar"
    command: ["roslaunch", "ydlidar_ros_driver", "G2.launch"]
    environment:
      ROS_MASTER_URI: http://core:11311
    networks:
    - ros

  # cameraNode publishes main camera frames to ROS topic
  cameraNode:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/ros:latest
    restart: always
    working_dir: /var/code
    volumes:
    - ./:/var/code
    devices:
      - "/dev/video8:/dev/video0"
    command: ["roslaunch", "./launch/camera.launch"]
    environment:
      ROS_MASTER_URI: http://core:11311
    networks:
    - ros

  gpsNode:
    depends_on:
    - core
    image: registry.digitalocean.com/streetbot/ros:latest
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/var/code
    devices:
      - "/dev/ttyUSB2:/dev/ttyUSB2"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    command: ["/bin/bash", "/var/code/scripts/start_gps.sh"]
    environment:
      ROS_MASTER_URI: http://core:11311
    networks:
    - ros

networks:
  ros:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
