signalEndpoint: "ws://localhost:8080"
signalURL: "http://localhost:8080"
id: streetbot-1
ros:
    nodeName: "/web"
    args: []
log:
    level: info
multimedia:
    enabled: true
    camera:
        device: /dev/video1
        format: "video/x-raw,format=I420,width=640,height=480 ! queue ! x264enc" # For local v4l2loopback
        track: video
    tracks:
        video: VP8