name: deploy

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and run go-semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o /tmp/semantic-release && chmod +x /tmp/semantic-release
          set +e  # Don't exit on the any error (for semantic-release)
          /tmp/semantic-release --token $GITHUB_TOKEN --slug "street-bot/robot"
          set -e  # Don't exit on the any error (for semantic-release)
          if [[ $? == 65 ]]; then
            echo -e "::set-output name=NewRelease::false"
          else
            echo -e "::set-output name=NewRelease::true"
          fi
      - name: Get latest tag
        if: steps.semantic-release.outputs.NewRelease == 'true'
        run: |
          git pull
      - name: Build and release
        if: steps.semantic-release.outputs.NewRelease == 'true'
        env:
          GOPRIVATE: "github.com/street-bot"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          sudo apt update && sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good gstreamer1.0-libav
          curl -sL https://git.io/goreleaser | bash
